### ISSUE TITLE
Can not instal on ubuntu 24

### ISSUE THREAD

**Issue by NailGit** [lafrech/qbirthday#18]
Hi, 
the installation commands `pip install qbirthday` gives error below. In ubuntu 22 it worked well. 
```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by lafrech** [comment]
This is not related to qbirthday.

This is what happens now when installing a package with pip in
system Python installation (to avoid wreaking havoc there by mistake).
This enforces the good practice of using virtual environments for
packages that are not managed by Debian.

You should follow the advice in the error message and create a virtual
environment.

**Comment by NailGit** [comment]
> This is not related to qbirthday. This is what happens now when installing a package with pip in system Python installation (to avoid wreaking havoc there by mistake). This enforces the good practice of using virtual environments for packages that are not managed by Debian. You should follow the advice in the error message and create a virtual environment.

Thank you. I made `pip install qbirthday` in separate virtual environment. Qbirthday starts, but when I click on icon in the tray it disappears with the following error
```
Traceback (most recent call last):
  File "/home/nail/Progi/Gbirthday/qb/lib/python3.12/site-packages/qbirthday/mainwindow.py", line 51, in showEvent
    self.move(systray_icon_pos.x() - self.width() / 2, systray_icon_pos.y())
TypeError: arguments did not match any overloaded call:
  move(self, a0: QPoint): argument 1 has unexpected type 'float'
  move(self, ax: int, ay: int): argument 1 has unexpected type 'float'
Emergency stops (the image of the memory is dropped to the disk)
```

**Comment by lafrech** [comment]
This was fixed a while back. See #17.

Please double-check the version you installed (pip freeze). The latest 
version is 0.7.1.

**Comment by NailGit** [comment]
> This was fixed a while back. See #17. Please double-check the version you installed (pip freeze). The latest version is 0.7.1.

I just repeated installation. It works well now. Thank you.
